// Dados dos carros
const cars = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    mileage: 35000,
    price: 85000,
    fuelType: "Flex",
    transmission: "Automática",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Toyota+Corolla",
    featured: true,
    description: "O Toyota Corolla é um sedan confiável e econômico com recursos modernos e interior confortável.",
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2023,
    mileage: 15000,
    price: 110000,
    fuelType: "Flex",
    transmission: "Automática",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Honda+Civic",
    featured: false,
    description:
      "O Honda Civic oferece excelente economia de combustível, interior espaçoso e recursos avançados de segurança.",
  },
  {
    id: 3,
    make: "Fiat",
    model: "Pulse",
    year: 2023,
    mileage: 8000,
    price: 95000,
    fuelType: "Flex",
    transmission: "Automática",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Fiat+Pulse",
    featured: true,
    description: "O Fiat Pulse é um SUV compacto com design moderno e ótimo desempenho urbano.",
  },
  {
    id: 4,
    make: "Volkswagen",
    model: "Gol",
    year: 2021,
    mileage: 50000,
    price: 60000,
    fuelType: "Flex",
    transmission: "Manual",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Volkswagen+Gol",
    featured: false,
    description: "O Volkswagen Gol é um hatch compacto, econômico e ideal para o dia a dia na cidade.",
  },
  {
    id: 5,
    make: "Chevrolet",
    model: "Onix",
    year: 2024,
    mileage: 2000,
    price: 75000,
    fuelType: "Flex",
    transmission: "Automática",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Chevrolet+Onix",
    featured: true,
    description: "O Chevrolet Onix é um dos carros mais vendidos do Brasil, com ótimo custo-benefício.",
  },
  {
    id: 6,
    make: "Hyundai",
    model: "HB20",
    year: 2022,
    mileage: 40000,
    price: 70000,
    fuelType: "Flex",
    transmission: "Manual",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Hyundai+HB20",
    featured: false,
    description: "O Hyundai HB20 combina design moderno, economia e conforto em um pacote compacto.",
  },
  {
    id: 7,
    make: "Jeep",
    model: "Compass",
    year: 2023,
    mileage: 12000,
    price: 150000,
    fuelType: "Flex",
    transmission: "Automática",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Jeep+Compass",
    featured: true,
    description: "O Jeep Compass oferece capacidade off-road, luxo e tecnologia em um SUV médio.",
  },
  {
    id: 8,
    make: "Renault",
    model: "Kwid",
    year: 2021,
    mileage: 60000,
    price: 50000,
    fuelType: "Flex",
    transmission: "Manual",
    image: "https://placehold.co/600x400/7c3aed/FFFFFF?text=Renault+Kwid",
    featured: false,
    description: "O Renault Kwid é um subcompacto com ótimo espaço interno e baixo consumo de combustível.",
  },
]

